name: Deploy EKS Portal with ALB via OIDC

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: k8s-practice-cluster
  ECR_REPOSITORY: eks-portal

jobs:
  build-and-deploy:
    name: Build & Ship to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::230235764463:role/GitHubActions-EKSTest
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag & Push Docker Image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image_uri=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3

      - name: Connect to EKS Cluster
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Deploy Manifests & Update Image
        env:
          IMAGE_URI: ${{ steps.build-image.outputs.image_uri }}
        run: |
          # 1. Sare Kubernetes Manifests apply karein (Deployment, Service, ALB Ingress)
          kubectl apply -f k8s/

          # 2. Deployment ko nayi image ke sath update karein
          kubectl set image deployment/eks-portal-deployment eks-portal-container=$IMAGE_URI -n portal-system

          # 3. Rolling update check karein
          kubectl rollout status deployment/eks-portal-deployment -n portal-system --timeout=120s

      - name: Print ALB Ingress URL
        run: |
          echo "Waiting for ALB to generate DNS address..."
          sleep 15
          kubectl get ingress -n portal-system
